/** Excel review pack for the invoices-on-hold workbench, assembled entirely
 * in the browser: summary, aging by reason and age bucket, the supplier-wise
 * invoice list with statuses, and the per-invoice activity log. */
import * as XLSX from 'xlsx'
import {
  CATEGORY_LABELS,
  agingSummary,
  categorySummary,
  daysSince,
} from './holds'
import type { HoldsReport } from './holds'
import {
  DEFAULT_HOLD_STATUS,
  HOLD_STATUS_LABELS,
  loadActivity,
  loadEmailSentAt,
  loadHoldStatuses,
} from './holdsStore'

const MONEY_FORMAT = '#,##0.00;[Red]-#,##0.00'

type Cell = string | number | boolean

function money(cents: number): number {
  return cents / 100
}

function formatMoneyColumns(ws: XLSX.WorkSheet, columns: number[], headerRows = 1): void {
  const range = XLSX.utils.decode_range(ws['!ref'] ?? 'A1')
  for (let r = range.s.r + headerRows; r <= range.e.r; r++) {
    for (const c of columns) {
      const cell = ws[XLSX.utils.encode_cell({ r, c })] as XLSX.CellObject | undefined
      if (cell && cell.t === 'n') cell.z = MONEY_FORMAT
    }
  }
}

function sheet(rows: Cell[][], moneyColumns: number[] = [], headerRows = 1): XLSX.WorkSheet {
  const ws = XLSX.utils.aoa_to_sheet(rows)
  formatMoneyColumns(ws, moneyColumns, headerRows)
  ws['!cols'] = rows[0]?.map((_, c) => ({
    wch: Math.min(50, Math.max(...rows.map((r) => String(r[c] ?? '').length), 8) + 2),
  }))
  if (headerRows === 1 && rows.length > 1) ws['!autofilter'] = { ref: ws['!ref'] ?? 'A1' }
  return ws
}

function summarySheet(report: HoldsReport, generatedAt: Date): XLSX.WorkSheet {
  const statuses = loadHoldStatuses(report.id)
  const openCount = report.suppliers
    .flatMap((s) => s.invoices)
    .filter((inv) => (statuses[inv.key] ?? DEFAULT_HOLD_STATUS) !== 'resolved').length
  const rows: Cell[][] = [
    ['Report ID', report.id],
    ['Report file', report.fileName],
    ['Loaded', report.loadedAt],
    ['Suppliers', report.suppliers.length],
    ['Invoices on hold', report.invoiceCount],
    ['Invoices not yet resolved', openCount],
    ['Total amount on hold', money(report.total)],
    ['Currencies', report.currencies.join(', ') || 'not stated'],
    ['Generated', generatedAt.toISOString()],
    ['Generated by', 'TieOut AP invoices-on-hold workbench — assembled in the browser'],
  ]
  const ws = sheet(rows, [], 0)
  const cell = ws[XLSX.utils.encode_cell({ r: 6, c: 1 })] as XLSX.CellObject | undefined
  if (cell && cell.t === 'n') cell.z = MONEY_FORMAT
  return ws
}

function agingSheet(report: HoldsReport): XLSX.WorkSheet {
  const rows: Cell[][] = [['Hold aging', 'Invoices', 'Amount on hold']]
  for (const r of agingSummary(report)) rows.push([r.bucket, r.count, money(r.total)])
  rows.push(['', '', ''])
  rows.push(['By hold reason', 'Invoices', 'Amount on hold'])
  for (const r of categorySummary(report)) rows.push([CATEGORY_LABELS[r.category], r.count, money(r.total)])
  const ws = XLSX.utils.aoa_to_sheet(rows)
  formatMoneyColumns(ws, [2])
  ws['!cols'] = [{ wch: 24 }, { wch: 10 }, { wch: 16 }]
  return ws
}

function invoicesSheet(report: HoldsReport): XLSX.WorkSheet {
  const statuses = loadHoldStatuses(report.id)
  const emailSentAt = loadEmailSentAt(report.id)
  const rows: Cell[][] = [
    [
      'Supplier',
      'Invoice',
      'PO',
      'Hold reason',
      'Hold type',
      'Buyer comments',
      'Amount on hold',
      'Currency',
      'Qty invoiced',
      'Qty received',
      'Hold date',
      'Days on hold',
      'Status',
      'Request emailed',
    ],
  ]
  for (const s of report.suppliers) {
    for (const inv of s.invoices) {
      rows.push([
        s.supplier,
        inv.invoice,
        inv.po,
        inv.holdReason,
        CATEGORY_LABELS[inv.category],
        inv.comments,
        inv.amount === null ? '' : money(inv.amount),
        inv.currency,
        inv.qtyInvoiced ?? '',
        inv.qtyReceived ?? '',
        inv.holdDate,
        daysSince(inv.holdDate) ?? '',
        HOLD_STATUS_LABELS[statuses[inv.key] ?? DEFAULT_HOLD_STATUS],
        emailSentAt[s.supplier] ?? '',
      ])
    }
  }
  return sheet(rows, [6])
}

function activitySheet(report: HoldsReport): XLSX.WorkSheet {
  const rows: Cell[][] = [['When', 'Supplier', 'Invoice', 'Event']]
  const invoiceByKey = new Map(
    report.suppliers.flatMap((s) => s.invoices.map((inv) => [inv.key, inv.invoice] as const)),
  )
  for (const entry of loadActivity(report.id)) {
    rows.push([
      entry.at,
      entry.supplier,
      entry.invoiceKey === '' ? '(all on request)' : (invoiceByKey.get(entry.invoiceKey) ?? entry.invoiceKey),
      entry.event,
    ])
  }
  if (rows.length === 1) rows.push(['', '', '', 'No activity recorded yet'])
  return sheet(rows)
}

function readMeSheet(report: HoldsReport): XLSX.WorkSheet {
  const rows: Cell[][] = [
    [`TieOut AP hold review pack — report ${report.id}`],
    [''],
    ['Sheets in this workbook:'],
    ['Summary', 'Report file, totals, and generation details.'],
    ['Aging', 'Invoices and amounts on hold by age bucket and by hold reason.'],
    ['Invoices on hold', 'Every invoice from the uploaded report, supplier-wise, with hold type, status, and days on hold.'],
    ['Activity log', 'Every action recorded in the workbench: emails marked sent, status changes, proof reviews.'],
    [''],
    ['All figures come from the uploaded report and integer-cent arithmetic in the'],
    ['browser. Statuses and the activity log are working notes recorded in the'],
    ['preparer\u2019s browser. Releasing a hold happens in your ERP, by you \u2014 TieOut AP'],
    ['holds no ERP credentials, writes to no accounting system, and sends no emails'],
    ['on your behalf.'],
  ]
  const ws = XLSX.utils.aoa_to_sheet(rows)
  ws['!cols'] = [{ wch: 18 }, { wch: 95 }]
  return ws
}

/** Downloads the hold review pack workbook. */
export function downloadHoldPackXlsx(report: HoldsReport): void {
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, summarySheet(report, new Date()), 'Summary')
  XLSX.utils.book_append_sheet(wb, agingSheet(report), 'Aging')
  XLSX.utils.book_append_sheet(wb, invoicesSheet(report), 'Invoices on hold')
  XLSX.utils.book_append_sheet(wb, activitySheet(report), 'Activity log')
  XLSX.utils.book_append_sheet(wb, readMeSheet(report), 'Read Me')
  const slug = report.fileName.replace(/\.[^.]+$/, '').replace(/[^A-Za-z0-9]+/g, '-').replace(/^-|-$/g, '')
  XLSX.writeFile(wb, `tieout-hold-pack-${slug || report.id}.xlsx`)
}
