/** Golden fixture parity: the TS engine must produce byte-identical JSON to
 * the Python reference engine (fixtures/golden.json is generated by the
 * Python CLI and committed). */
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { DEFAULT_CONFIG, reconcile } from "../src/engine";
import { loadLedgerCsv, loadStatementCsv } from "../src/loader";
import { renderText, toJson } from "../src/serialize";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SUPPLIER = "MERIDIAN IND SUPPLIES";
const AS_AT = "2026-07-31";

function load() {
  return {
    statement: loadStatementCsv(
      readFileSync(join(ROOT, "fixtures", "meridian_stmt.csv"), "utf-8"),
    ),
    ledger: loadLedgerCsv(
      readFileSync(join(ROOT, "fixtures", "acme_ledger.csv"), "utf-8"),
    ),
  };
}

describe("golden fixture", () => {
  it("produces JSON byte-identical to the Python reference engine", () => {
    const { statement, ledger } = load();
    const result = reconcile(statement, ledger, SUPPLIER, AS_AT);
    const golden = readFileSync(join(ROOT, "fixtures", "golden.json"), "utf-8");
    expect(toJson(result)).toBe(golden);
  });

  it("produces a text report byte-identical to the Python reference engine", () => {
    const { statement, ledger } = load();
    const result = reconcile(statement, ledger, SUPPLIER, AS_AT);
    const golden = readFileSync(join(ROOT, "fixtures", "golden.txt"), "utf-8");
    expect(renderText(result)).toBe(golden);
  });

  it("bridge ties to the penny", () => {
    const { statement, ledger } = load();
    const result = reconcile(statement, ledger, SUPPLIER, AS_AT);
    expect(result.bridge.ties_out).toBe(true);
    expect(result.bridge.ledger_open_total).toBe(3_469_600);
    expect(result.bridge.statement_total).toBe(5_916_500);
    let adjustments = 0;
    for (const a of result.bridge.adjustments) adjustments += a.amount;
    expect(3_469_600 + adjustments).toBe(5_916_500);
    expect(result.diagnostic).toBeNull();
    expect(result.findings).toHaveLength(6);
    expect(result.proposed_rules).toHaveLength(1);
    expect(result.proposed_rules[0]!.value).toBe("MER-");
  });

  it("is byte-identical under shuffled input rows", () => {
    const { statement, ledger } = load();
    const baseline = toJson(reconcile(statement, ledger, SUPPLIER, AS_AT));
    for (const seed of [1, 7, 42]) {
      // Deterministic LCG shuffle
      let state = seed;
      const rand = () => {
        state = (state * 1103515245 + 12345) % 2147483648;
        return state / 2147483648;
      };
      const shuffle = <T>(xs: T[]): T[] => {
        const a = [...xs];
        for (let i = a.length - 1; i > 0; i--) {
          const j = Math.floor(rand() * (i + 1));
          [a[i], a[j]] = [a[j]!, a[i]!];
        }
        return a;
      };
      const got = toJson(
        reconcile(shuffle(statement), shuffle(ledger), SUPPLIER, AS_AT),
      );
      expect(got).toBe(baseline);
    }
  });

  it("warns when ledger as-at differs", () => {
    const { statement, ledger } = load();
    const result = reconcile(
      statement, ledger, SUPPLIER, AS_AT, DEFAULT_CONFIG, "2026-08-05",
    );
    expect(result.warnings).toHaveLength(1);
    expect(result.warnings[0]).toContain("2026-08-05");
  });
});
